# Generated by Django 4.0 on 2021-12-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BE', 'BEVERAGE'), ('CF', 'CANNED FOODS'), ('DP', 'DAIRY PRODUCTS'), ('FF', 'FROZEN FOODS'), ('PC', 'PERSONAL CARE')], default='BE', max_length=2),
        ),
    ]
