# Generated by Django 4.0 on 2021-12-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BE', 'BEVERAGE'), ('CF', 'CANNED GOODS'), ('DP', 'DAIRY PRODUCTS'), ('FF', 'FROZEN FOODS'), ('PC', 'PERSONAL CARE'), ('CM', 'CLEANING MATERIAL')], default='BE', max_length=2),
        ),
    ]
