# Generated by Django 4.0 on 2021-12-11 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('pending_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_order_item', to='core.item')),
            ],
        ),
    ]
