# Generated by Django 4.0 on 2021-12-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pendingorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingorder',
            options={'verbose_name_plural': 'Pending Orders'},
        ),
    ]
