# Generated by Django 4.0 on 2021-12-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pendingorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(50, 50), (100, 100), (150, 150)], default=50, max_length=3)),
                ('code', models.CharField(blank=True, max_length=8, null=True)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
