# Generated by Django 4.0 on 2021-12-12 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_coupon_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_number', models.CharField(blank=True, max_length=8, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='core.coupon')),
                ('transactions', models.ManyToManyField(related_name='pending_transactions', to='core.PendingOrder')),
            ],
        ),
    ]
