# Generated by Django 4.0 on 2021-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('PE', 'PENDING'), ('CO', 'COMPLETED'), ('RE', 'REFUNDED'), ('CA', 'CANCELED'), ('MO', 'MODIFIED')], default='PE', max_length=2),
        ),
    ]
