# Generated by Django 4.0 on 2021-12-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transaction_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingorder',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
