# Generated by Django 4.0 on 2021-12-12 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_transaction_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactions',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_transaction', to='core.pendingorder'),
        ),
    ]
