# Generated by Django 4.0 on 2021-12-12 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_transaction_transactions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_coupon', to='core.coupon')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_item', to='core.item')),
                ('pending_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_pending_order', to='core.pendingorder')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log_transaction', to='core.transaction')),
            ],
        ),
    ]
