# Generated by Django 4.0 on 2021-12-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name_plural': 'Activity Logs'},
        ),
    ]
