# Generated by Django 4.0 on 2021-12-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_pendingorder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED'), ('CANCELED', 'CANCELED'), ('RETURNED', 'RETURNED')], default='PENDING', max_length=9),
        ),
    ]
